version: '3'
services:
  app:
    image: gambero:latest
    depends_on:
      - db
    environment:
      - RAILS_ENV # One of "development", "test", "production"
    volumes:
      - .:/gambero
    networks:
      default:
        ipv4_address: 172.20.0.2
  db:
    image: mariadb
    volumes:
      - ./mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    networks:
      default:
        ipv4_address: 172.20.0.3

networks:
  default:
    ipam:
      config:
        - subnet: 172.20.0.0/24
