format_version: 3
pipelines:
  Gambero1:
    group: defaultGroup
    label_template: ${COUNT}
    lock_behavior: unlockWhenFinished
    materials:
      git:
        git: https://github.com/gambe-ro/lobsters
        shallow_clone: false
        auto_update: true
        branch: cd-fixes
        destination: gambero
    stages:
    - Deploy:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
        jobs:
          docker-compose_restart:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - -c
                - cp -v /vagrant/.env .env && script/docker-reload.sh
                command: bash
                working_directory: gambero
                run_if: passed

