development:
  configuration_file: "/tmp/development.sphinx.conf"
  indices_location: "/sphinx/development"

production:
  configuration_file: "/tmp/production.sphinx.conf"
  indices_location: "/sphinx/production"
